[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# Whether to consider the binaries in a package for distribution (defaults true)
dist = true
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Which actions to run on pull requests
pr-run-mode = "plan"
# Post-announce jobs to run in CI
post-announce-jobs = ["./post-announce"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Build only the required packages, and individually
precise-builds = true
# Don't create GitHub releases, we handle that manually to manually control which release is marked as latest
create-release = false
# Use the stage just after plan because we need its output to create the draft release
local-artifacts-jobs = ["./create-draft-release"]
# Uncomment this to rerun `dist generate`
# ⚠️ This will overwrite any manual changes to generated files, make sure to re-apply them if they're still relevant
# We need this to prevent gh release edit from marking any release as latest, but cargo-dist does not support that customizing this yet
# https://github.com/axodotdev/cargo-dist/issues/2244
allow-dirty = ["ci"]

[dist.github-custom-runners]
aarch64-unknown-linux-musl = "buildjet-2vcpu-ubuntu-2204-arm"
