[package]
name = "exec-harness"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/CodSpeedHQ/runner"
publish = false

[dependencies]
anyhow = { workspace = true }
codspeed = "4.1.0"
clap = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[package.metadata.dist]
targets = ["aarch64-unknown-linux-musl", "x86_64-unknown-linux-musl"]
