[package]
name = "exec-harness"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
codspeed = "4.1.0"
clap = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
